// <auto-generated />
using System;
using AkimElemLib.Wpf.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkimElemLib.Wpf.DataAccess.Migrations
{
    [DbContext(typeof(AkimElemLibContext))]
    [Migration("20230427120959_Create_Obstacle_Entity")]
    partial class Create_Obstacle_Entity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("AkimElemLib.Wpf.Models.CctvCams.StationaryCctvCam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Alpha")
                        .HasColumnType("REAL");

                    b.Property<double>("AlphaMax")
                        .HasColumnType("REAL");

                    b.Property<double>("AlphaMin")
                        .HasColumnType("REAL");

                    b.Property<double>("Beta")
                        .HasColumnType("REAL");

                    b.Property<double>("DetectionProbability")
                        .HasColumnType("REAL");

                    b.Property<double>("Fps")
                        .HasColumnType("REAL");

                    b.Property<bool>("HasVideoAnalytics")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageResolutionHorizontal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageResolutionVertical")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InstallationHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("LightSensitivity")
                        .HasColumnType("REAL");

                    b.Property<double>("MatrixDiagonalHorizontal")
                        .HasColumnType("REAL");

                    b.Property<double>("MatrixDiagonalVertical")
                        .HasColumnType("REAL");

                    b.Property<int>("MatrixFormat")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxTemperature")
                        .HasColumnType("REAL");

                    b.Property<double>("MinReactionTime")
                        .HasColumnType("REAL");

                    b.Property<double>("MinTemperature")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Omega")
                        .HasColumnType("REAL");

                    b.Property<double>("Phi")
                        .HasColumnType("REAL");

                    b.Property<double>("PowerConsumptionWatts")
                        .HasColumnType("REAL");

                    b.Property<int>("PowerSupplyType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WorkingVoltage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("StationaryCctvCam", (string)null);
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.ISOs.Barrier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightRelativeToGround")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRamResistant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSurmountableByResponseTeams")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxOvercomeTime")
                        .HasColumnType("REAL");

                    b.Property<double>("MinOvercomeTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Transparency")
                        .HasColumnType("REAL");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Barrier", (string)null);
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.ISOs.Fence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAluminiumBarbedTape")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBase")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRamResistant")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxOvercomeTime")
                        .HasColumnType("REAL");

                    b.Property<double>("MinOvercomeTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Transparency")
                        .HasColumnType("REAL");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Fence", (string)null);
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.ISOs.Obstacle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAluminiumBarbedTape")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBase")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightRelativeToGround")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsRamResistant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSurmountableByResponseTeams")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxEntranceDelay")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxExitDelay")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxOvercomeTime")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxVelocity")
                        .HasColumnType("REAL");

                    b.Property<double>("MinEntranceDelay")
                        .HasColumnType("REAL");

                    b.Property<double>("MinExitDelay")
                        .HasColumnType("REAL");

                    b.Property<double>("MinOvercomeTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Transparency")
                        .HasColumnType("REAL");

                    b.Property<int>("VelocityMeasureUnit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Obstacle", (string)null);
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.Intruders.Intruder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("DropEquipmentProbability")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Intruder", (string)null);
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.SpecificObjects.SpecificObjectBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightRelativeToGround")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxVelocity")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Transparency")
                        .HasColumnType("REAL");

                    b.Property<int>("VelocityMeasureUnit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SpecificObjectBase", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("SpecificObjectBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.SpecificObjects.AerialConstructions.AerialConstruction", b =>
                {
                    b.HasBaseType("AkimElemLib.Wpf.Models.SpecificObjects.SpecificObjectBase");

                    b.HasDiscriminator().HasValue("AerialConstruction");
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.SpecificObjects.Buildings.Building", b =>
                {
                    b.HasBaseType("AkimElemLib.Wpf.Models.SpecificObjects.SpecificObjectBase");

                    b.HasDiscriminator().HasValue("Building");
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.SpecificObjects.SpecificAreas.SpecificArea", b =>
                {
                    b.HasBaseType("AkimElemLib.Wpf.Models.SpecificObjects.SpecificObjectBase");

                    b.HasDiscriminator().HasValue("SpecificArea");
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.CctvCams.StationaryCctvCam", b =>
                {
                    b.OwnsOne("AkimElemLib.Wpf.Models.CctvCams.CctvCamVariofocalLensParams", "VariofocalLensParams", b1 =>
                        {
                            b1.Property<Guid>("StationaryCctvCamId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("MaxFocalLength")
                                .HasColumnType("REAL");

                            b1.Property<double>("MinFocalLength")
                                .HasColumnType("REAL");

                            b1.HasKey("StationaryCctvCamId");

                            b1.ToTable("StationaryCctvCam");

                            b1.WithOwner()
                                .HasForeignKey("StationaryCctvCamId");
                        });

                    b.Navigation("VariofocalLensParams")
                        .IsRequired();
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.ISOs.Fence", b =>
                {
                    b.OwnsOne("AkimElemLib.Wpf.Models.ISOs.FenceBottomParams", "BottomParams", b1 =>
                        {
                            b1.Property<Guid>("FenceId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Depth")
                                .HasColumnType("REAL");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("SendsVibrations")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("SendsVibrationsToMainSurface")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Width")
                                .HasColumnType("REAL");

                            b1.HasKey("FenceId");

                            b1.ToTable("Fence");

                            b1.WithOwner()
                                .HasForeignKey("FenceId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.ISOs.FenceMainSurfaceParams", "MainSurfaceParams", b1 =>
                        {
                            b1.Property<Guid>("FenceId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Height")
                                .HasColumnType("REAL");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("SendsVibrations")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Width")
                                .HasColumnType("REAL");

                            b1.HasKey("FenceId");

                            b1.ToTable("Fence");

                            b1.WithOwner()
                                .HasForeignKey("FenceId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.ISOs.FenceTopParams", "TopParams", b1 =>
                        {
                            b1.Property<Guid>("FenceId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Height")
                                .HasColumnType("REAL");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("SendsVibrations")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("SendsVibrationsToMainSurface")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Width")
                                .HasColumnType("REAL");

                            b1.HasKey("FenceId");

                            b1.ToTable("Fence");

                            b1.WithOwner()
                                .HasForeignKey("FenceId");
                        });

                    b.Navigation("BottomParams")
                        .IsRequired();

                    b.Navigation("MainSurfaceParams")
                        .IsRequired();

                    b.Navigation("TopParams")
                        .IsRequired();
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.ISOs.Obstacle", b =>
                {
                    b.OwnsOne("AkimElemLib.Wpf.Models.ISOs.ObstacleAntiUndercarriageDeviceParams", "AntiUndercarriageDeviceParams", b1 =>
                        {
                            b1.Property<Guid>("ObstacleId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Depth")
                                .HasColumnType("REAL");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ObstacleId");

                            b1.ToTable("Obstacle");

                            b1.WithOwner()
                                .HasForeignKey("ObstacleId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.ISOs.ObstacleVisorFenceParams", "VisorFenceParams", b1 =>
                        {
                            b1.Property<Guid>("ObstacleId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Height")
                                .HasColumnType("REAL");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ObstacleId");

                            b1.ToTable("Obstacle");

                            b1.WithOwner()
                                .HasForeignKey("ObstacleId");
                        });

                    b.Navigation("AntiUndercarriageDeviceParams")
                        .IsRequired();

                    b.Navigation("VisorFenceParams")
                        .IsRequired();
                });

            modelBuilder.Entity("AkimElemLib.Wpf.Models.Intruders.Intruder", b =>
                {
                    b.OwnsOne("AkimElemLib.Wpf.Models.Intruders.IntruderEquipmentParams", "HeavyEquipment", b1 =>
                        {
                            b1.Property<Guid>("IntruderId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("ObstacleOvercomeTimeDecreaseCoefficient")
                                .HasColumnType("REAL");

                            b1.Property<double>("VelocityDecreaseCoefficient")
                                .HasColumnType("REAL");

                            b1.HasKey("IntruderId");

                            b1.ToTable("Intruder");

                            b1.WithOwner()
                                .HasForeignKey("IntruderId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.Intruders.IntruderDimensionsParams", "HeightParams", b1 =>
                        {
                            b1.Property<Guid>("IntruderId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CrawlingMm")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DeepSquatMm")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FullHeightMm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("IntruderId");

                            b1.ToTable("Intruder");

                            b1.WithOwner()
                                .HasForeignKey("IntruderId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.Intruders.IntruderDimensionsParams", "LengthParams", b1 =>
                        {
                            b1.Property<Guid>("IntruderId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CrawlingMm")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DeepSquatMm")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FullHeightMm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("IntruderId");

                            b1.ToTable("Intruder");

                            b1.WithOwner()
                                .HasForeignKey("IntruderId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.Intruders.IntruderEquipmentParams", "LightEquipment", b1 =>
                        {
                            b1.Property<Guid>("IntruderId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("ObstacleOvercomeTimeDecreaseCoefficient")
                                .HasColumnType("REAL");

                            b1.Property<double>("VelocityDecreaseCoefficient")
                                .HasColumnType("REAL");

                            b1.HasKey("IntruderId");

                            b1.ToTable("Intruder");

                            b1.WithOwner()
                                .HasForeignKey("IntruderId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.Intruders.IntruderEquipmentParams", "MediumEquipment", b1 =>
                        {
                            b1.Property<Guid>("IntruderId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("ObstacleOvercomeTimeDecreaseCoefficient")
                                .HasColumnType("REAL");

                            b1.Property<double>("VelocityDecreaseCoefficient")
                                .HasColumnType("REAL");

                            b1.HasKey("IntruderId");

                            b1.ToTable("Intruder");

                            b1.WithOwner()
                                .HasForeignKey("IntruderId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.Intruders.IntruderDimensionsParams", "WidthParams", b1 =>
                        {
                            b1.Property<Guid>("IntruderId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CrawlingMm")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DeepSquatMm")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FullHeightMm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("IntruderId");

                            b1.ToTable("Intruder");

                            b1.WithOwner()
                                .HasForeignKey("IntruderId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.Intruders.IntruderAccomplicesParams", "AccomplicesParams", b1 =>
                        {
                            b1.Property<Guid>("IntruderId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("HasAccomplices")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Iso2xDelayDropProbability")
                                .HasColumnType("REAL");

                            b1.Property<double>("Sensors2xDetectionDecreaseProbability")
                                .HasColumnType("REAL");

                            b1.Property<double>("TimeTillIntentionalFalseAlarm")
                                .HasColumnType("REAL");

                            b1.HasKey("IntruderId");

                            b1.ToTable("Intruder");

                            b1.WithOwner()
                                .HasForeignKey("IntruderId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.Intruders.IntruderCarParams", "CarParams", b1 =>
                        {
                            b1.Property<Guid>("IntruderId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("CarDropProbability")
                                .HasColumnType("REAL");

                            b1.Property<bool>("HasCar")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("VelocityIncreaseCoefficient")
                                .HasColumnType("REAL");

                            b1.HasKey("IntruderId");

                            b1.ToTable("Intruder");

                            b1.WithOwner()
                                .HasForeignKey("IntruderId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.Intruders.IntruderPsychophysicalParams", "PsychophysicalParams", b1 =>
                        {
                            b1.Property<Guid>("IntruderId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("AerialConstructionIntrusionProbability")
                                .HasColumnType("REAL");

                            b1.Property<double>("CautionDropTo0Probability")
                                .HasColumnType("REAL");

                            b1.Property<double>("IntrusionRefusalProbability")
                                .HasColumnType("REAL");

                            b1.Property<double>("MaxRunawayDistance")
                                .HasColumnType("REAL");

                            b1.Property<double>("MinRunawayDistance")
                                .HasColumnType("REAL");

                            b1.Property<double>("MovementDirectionChangeProbability")
                                .HasColumnType("REAL");

                            b1.Property<int>("ObjectTerritoryKnowledgePercent")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("UnnoticedIntrusionProbability")
                                .HasColumnType("REAL");

                            b1.Property<double>("VelocityChangeProbability")
                                .HasColumnType("REAL");

                            b1.Property<double>("VelocityIncreaseProbability")
                                .HasColumnType("REAL");

                            b1.HasKey("IntruderId");

                            b1.ToTable("Intruder");

                            b1.WithOwner()
                                .HasForeignKey("IntruderId");
                        });

                    b.OwnsOne("AkimElemLib.Wpf.Models.Intruders.IntruderVelocityParams", "VelocityParams", b1 =>
                        {
                            b1.Property<Guid>("IntruderId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("MaxVelocity")
                                .HasColumnType("REAL");

                            b1.Property<double>("MinVelocity")
                                .HasColumnType("REAL");

                            b1.Property<int>("VelocityMeasureUnit")
                                .HasColumnType("INTEGER");

                            b1.HasKey("IntruderId");

                            b1.ToTable("Intruder");

                            b1.WithOwner()
                                .HasForeignKey("IntruderId");
                        });

                    b.Navigation("AccomplicesParams")
                        .IsRequired();

                    b.Navigation("CarParams")
                        .IsRequired();

                    b.Navigation("HeavyEquipment")
                        .IsRequired();

                    b.Navigation("HeightParams")
                        .IsRequired();

                    b.Navigation("LengthParams")
                        .IsRequired();

                    b.Navigation("LightEquipment")
                        .IsRequired();

                    b.Navigation("MediumEquipment")
                        .IsRequired();

                    b.Navigation("PsychophysicalParams")
                        .IsRequired();

                    b.Navigation("VelocityParams")
                        .IsRequired();

                    b.Navigation("WidthParams")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
